In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
%config InlineBackend.figure_format = 'retina'



# **Creating Arrays**

#### 1. Create a 1D array with 20 random integers between 1 and 100.
**Hint:** Use the `np.random.randint()` function, specifying the range and size.
#### 2. Create a 5x5 matrix where all the border elements are 1, and the inside elements are 0.
#### 3. Create a diagonal matrix with values `[1, 2, 3, 4]` on the diagonal.
#### 4. Create an array of shape (3, 3) where each row contains numbers from 1 to 3.
**Hint:** Use `np.tile()` to repeat arrays along rows or columns.
#### 5. Create a 1D array with alternating 0s and 1s of length 10.
#### 6. Create a 3x3 matrix with random integers between 10 and 20, and set the datatype to `int32`.

```
# This is formatted as code
```



In [ ]:
import numpy as np
y=np.random.randint(1,100,20)
print(y)

[86 47 86 83 45 72 94 42 84 90 80 29 80 60 89 52 61 55 43 33]


In [ ]:
np.__version__

'1.26.4'

In [ ]:
import numpy as np
grid=np.array([1 ,1, 1, 1 ,1, 1 ,0 ,0, 0, 1, 1, 0 ,0, 0, 1, 1, 0, 0 ,0 ,1, 1, 1, 1 ,1, 1])
grid.reshape(5,5)
print(grid.reshape(5,5))


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
import numpy as np
diagnol_matrix=np.diag([1,2,3,4])
print(diagnol_matrix)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [ ]:
import numpy as np
row=np.array([1,2,3])
matrix=np.tile(row,(3,1))
print(matrix)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
import numpy as np
chain=np.array([1,0])
matrix=np.tile(chain,(1,5))
print(matrix)

[[1 0 1 0 1 0 1 0 1 0]]


In [ ]:
import numpy as np
matrix=np.random.randint(10,21,(3,3)),np.int32
print(matrix)


(array([[18, 15, 13],
       [16, 17, 11],
       [11, 18, 11]]), <class 'numpy.int32'>)


# **Array Attributes**

####1. Create a NumPy array of shape (4, 5) filled with random integers between 1 and 10. Now use an appropriate attribute of an array and find the following:

  1. shape of the array
  2. size of the array
  3. number of dimensions
  4. data type

####2. Write a Python function that takes an array as input and returns the number of dimensions (ndim) of the array.
Test the function with the following arrays:

  1. A 1D array with 5 elements.
  2. A 2D array of size (3x4).
  3. A 3D array of size (2x3x4).


####3. Create a NumPy array with the elements between 1 to 100 and use the dtype attribute to find out the data type of the elements. Modify the program to create arrays with elements of type float and string, and observe the changes in dtype.

####4. Write a Python function that:
  1. Creates a 6×3 array of integers using NumPy.
  2. Prints the shape of the array using the shape attribute.
  3. Reshapes the array to 3×6 and prints the new shape.



####5. Write a program to:
  1. Create an array of any size with all elements being 0 and use the appropriate attribute to print the size (in bytes) of each element in the array.
  2. Create an array of any size with elements between 1 to 10 and print the size.
  3. Create another array with floating-point numbers of any size and observe how the size changes.



In [30]:
import numpy as np
matrix=np.random.randint(1,11,(4,5))
print(matrix)
print(np.sum(matrix,axis=1))
print(matrix.shape)
print(matrix.size)
print(matrix.ndim)
print(matrix.dtype)

[[ 7 10  6  4  8]
 [ 3  6  8  6  1]
 [ 6  6  6  9  8]
 [ 1  2  5  9 10]]
[35 24 35 27]
(4, 5)
20
2
int64


In [42]:
import numpy as np
def ndim(array):
  return array.ndim
array1=np.array([1,2,3,4,5])
array2=np.array([[1,2,3,4],[5,6,7,8]])
array3=np.random.randint(1,21,(2,3,4))
print(ndim(array1))
print(ndim(array2))
print(ndim(array3))





1
2
3


In [46]:
import numpy as py
a=np.arange(1,101)
print(a)
print(a.dtype)
b=a.astype(float)
#c=np.array(str(i) for i in range(1,101))
c=a.astype(str)
print(b.dtype)
print(c.dtype)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
int64
float64
<U21


In [33]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18])
arr_1=arr.reshape(6,3)
print(arr_1)
print(arr_1.shape)
arr_2=arr_1.reshape(3,6)
print(arr_2)
print(arr_2.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]
(6, 3)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]
(3, 6)


In [34]:
arr=np.zeros(10)
print(arr)
print(arr.itemsize)
matrix=np.random.randint(1,10,(4,5))
print(matrix)
print(matrix.size)
a=np.array([[0.0,1.0,1.0,2.0,3.0],[2.0,3.0,4.0,2.0,3.3],[5.0,6.0,7.0,2.0,4.5],[8.0,9.0,10.0,2.0,5.8]])
print(a)
print(a.size)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
8
[[1 6 9 3 8]
 [2 8 2 4 4]
 [9 6 5 1 1]
 [9 6 1 2 4]]
20
[[ 0.   1.   1.   2.   3. ]
 [ 2.   3.   4.   2.   3.3]
 [ 5.   6.   7.   2.   4.5]
 [ 8.   9.  10.   2.   5.8]]
20


# **Sorting and Partioning**

####1. Given an array arr, sort the array in ascending order without modifying the original array. Print both the original and sorted arrays.(use np.sort())

####2. You have arr = np.array([50, 30, 40, 20]) and names = np.array(["A", "B", "C", "D"]).
Sort the arr values in ascending order and rearrange the names array accordingly.(use np.argsort() to get sorted indices and reorder names)

####3. Write code to find the k smallest elements from the array arr. Print these elements in ascending order.(use np.partition())

####4. Partition the array arr such that all elements smaller than a particular number(user input) appear before those greater than or equal to that number. Print the partitioned array.(use np.partition() to find the pivot value's index)

####5. Sort each row of a 2D array arr in ascending order.(use np.sort() with axis parameter)

####6. Print k largest elements of an array arr in descending order.(use np.partition() to find top k elements)

####7. Given an array arr(containing possible negative values), sort the array in ascending order based on the absolute values of the elements. Print the sorted array.(use np.argsort() with a custom key for absolute values)

####8. Given an array arr, sort only the elements greater than k in ascending order, keeping the other elements in their original positions.(create a mask to find elements greater than k, use np.sort() to sort them then reassign the sorted values back to their original indices in the array)

In [ ]:
#1
import numpy as np
arr=np.array([50,30,40,20])
arr.sort()
print(arr)

[20 30 40 50]


In [ ]:
#2
import numpy as np
arr=np.array([50,30,40,20])
names=np.array(["A","B","C","D"])
indices=arr.argsort()
sorted_names=names[indices]
print(sorted_names)
print(indices)


['D' 'B' 'C' 'A']
[3 1 2 0]



In [ ]:
#3
import numpy as np
k=int(input())
arr=np.array([50,30,40,20,5,14,56,78,9,34,43,11,56,0,1])
arr.sort()
indices=np.partition(arr,k)
smallest_k_elements = indices[:k]
print(smallest_k_elements)


print(indices)


5
[ 0  1  5  9 11]
[ 0  1  5  9 11 14 20 30 34 40 43 50 56 56 78]


In [ ]:
#8
arr=np.array([4,7,2,1,8,6,4])
k=5

mask=arr>=k
arr[mask]=np.sort(arr[mask])
elements=arr[mask]
print(elements)
print(mask)
print(arr)

[6 7 8]
[False  True False False  True  True False]
[4 6 2 1 7 8 4]


In [ ]:
#5
arr=np.array([[6,9,5],[1,4,2],[7,3,8]])
arr.sort(axis=0)#colums sort
arr.sort(axis=1)#row sort
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#6
k=int(input())
arr=np.array([50,30,40,20,5,14,56,78,9,34,43,11,56,0,1])
arr.sort()
indices=np.partition(arr,-k)
largest_k_elements = indices[-k:]
largest_k_elementsin_descending_order=np.sort(largest_k_elements)[::-1]
print(largest_k_elementsin_descending_order)

5
[78 56 56 50 43]


In [ ]:
#7
arr=np.array([1,-2,8,56,-27,6,-53])
arr=arr[np.argsort(np.abs(arr))]
print(arr)

[  1  -2   6   8 -27 -53  56]


In [47]:
#4
k=int(input())
arr=np.array([10,23,4,67,8,43,35,107])
pivot_index=np.sum(arr<k)
print('pivot_index:',pivot_index)
arr_required=np.partition(arr,np.sum(arr<k))
print(arr_required)


25
pivot_index: 4
[  8   4  10  23  35  43  67 107]


# **Indexing and slicing**

#### 1. 2D Array Indexing
Consider the following 2D array:
`arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])`
- Access the element at row index 1 and column index 2.
- Extract the first row.
- Extract the last column.

In [ ]:
import numpy as np

arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
print(arr_2d[1,2])
print(arr_2d[0,:])
print(arr_2d[:,2])

30
[ 5 10 15]
[15 30 45]


#### 2. Boolean Indexing
Given an array `arr = np.array([2, 5, 8, 11, 14, 17, 20])`, use boolean indexing to:
- Extract all values greater than 10.
- Replace all values greater than 15 with -1.

In [ ]:
arr = np.array([2, 5, 8, 11, 14, 17, 20])
data=arr>10
arr_required=arr[data]
print(arr_required)

arr_final = np.where(arr_required>15, -1, arr_required)
print(arr_final)

[11 14 17 20]
[11 14 -1 -1]


#### 3. Fancy Indexing
Using the 2D array `arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])`, write code to:

- Select the elements at positions (0,2), (1,1), and (2,0).
- Use fancy indexing to create a submatrix with rows 0 and 2, and columns 1 and 2.

- **Hint:**
 - For 1st part, use arrays of row and column indices
 - For 2nd part, you can create a submatrix using fancy indexing by using np.newaxis to match the dimensions


In [ ]:

import numpy as np
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])
print(arr_2d[0,2])
print(arr_2d[1,1])
print(arr_2d[2,0])
# Assuming you .want to add a new axis at the beginning. Replace axis=0 with desired axis if different.
##print(arr_2d[:, np.newaxis])
#print(arr_2d[np.newaxis,:])
print(arr_2d[0:3:2,1:3])


15
25
35
[[10 15]
 [40 45]]


#### 4. Slicing 1D array
Given the array `arr = np.array([1, 3, 5, 7, 9, 11, 13, 15])`, write code to:

- Extract the first 4 elements.
- Extract every second element from the entire array.
- Extract elements from index 2 to the end, stepping by 2.

In [ ]:
arr = np.array([1, 3, 5, 7, 9, 11, 13, 15])
print(arr[:4])
print(arr[::2])
print(arr[2::2])


[1 3 5 7]
[ 1  5  9 13]
[ 5  9 13]


#### 5. Slicing a 2D Array
Given the following 2D array:
`arr_2d = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])`
- Slice and print the last two columns of 1st row.
- Slice and print the last row, reversed.

In [ ]:
arr_2d = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 100, 110, 120]])

print(arr_2d[0,-2:])
print(arr_2d[-1,::-1])

[30 40]
[120 110 100  90]


#### 6. Handling Out-of-Range Indices in Slicing vs. Indexing
Given the array:
`arr = np.array([10, 20, 30, 40, 50])`


- What will be the output of the following slicing operations? Explain why they work, even though some indices are out of range.
 - print(arr[2:10])  
 - print(arr[-10:3])    

- Compare the behavior of slicing to accessing a single element with an out-of-range index (e.g., arr[10]). Why does slicing not raise an error in these cases, but indexing does?

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[2:10])
print(arr[-10:3])
# if "print(arr[10])" is written index errror will raise due to focusing of element of a specific index
#but the same won"t happen to slicing as numpy will adjust the range to valid range while coding as its main function is to give a sub array.
#it will extend beyond valid indices.

[30 40 50]
[10 20 30]


#### 7.  Work with an Audio File

Download the audio file from the following link: Simple Logo - Pixabay. Load the audio file using pydub and complete the following tasks:

- Extract the first second of the audio and plot its waveform.
   - Hint: Use the frame rate to calculate how many samples are in 1 second, and use slicing to extract this part.

-   Extract the last second of the audio and plot its waveform.
  

-  Combine the samples from the first second and the last second into a new array and plot the combined waveform.
 - Hint: Use NumPy’s np.concatenate() function to merge the two slices.

In [55]:
from pydub import AudioSegment
import numpy as np
import matplotlib.pyplot as plt
audio_file = "simple-logo-149190.mp3"
# audio = AudioSegment.from_file(audio_file)


audio = audio.set_channels(1)

frame_rate = audio.frame_rate

first_second = audio[:1000]
first_second_samples = np.array(first_second.get_array_of_samples())

last_second = audio[-1000:]
last_second_samples = np.array(last_second.get_array_of_samples())





NameError: name 'audio' is not defined

In [50]:
pip install pydub numpy matplotlib


# **Reshaping in NumPy**


####1. Create a 2D array of shape (3, 5). Flatten it into a 1D array and then reshape it back into a (5, 3) array.

####2. Create a 1D array
```
arr = np.array([1, 2, 3, 4, 5])
```
####Reshape arr into (5,1), then convert to (5,) and then convert it into (1,5).


####3. Create a 1D NumPy array with values ranging from 1 to 100. Reshape it into a (10, 10) matrix. Apply '.ravel()' and '.flatten()' on the matrix and modify the original matrix. Compare the outputs of both methods and explain the difference in memory sharing.


####4. Generate a 5x5 NumPy matrix representing pixel intensities from an image. Use slicing to extract the central 3x3 section of the matrix and flatten it. How does reshaping impact the spatial relationships of the pixels?


####5. Create a 3-channel RGB image as a NumPy array of shape (3, 4, 4) with random integer values between 0 and 255. Flatten the image using '.reshape()' and reshape it back to its original shape. Explain the order of pixel data stored and how reshaping affects the channel structure.



In [ ]:
#1
import numpy as np
arr=np.array([[1,2,3,4,5,],[6,7,8,9,10],[11,12,13,14,15]])
print(arr)
arr_flattened=arr.flatten()
print(arr_flattened)
arr_reshaped=arr_flattened.reshape(5,3)
print(arr_reshaped)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [ ]:
#2
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr=arr.reshape(5,1)
print(arr)
arr=arr.reshape(5,)
print(arr)
arr=arr.reshape(1,5)
print(arr)

[[1]
 [2]
 [3]
 [4]
 [5]]
[1 2 3 4 5]
[[1 2 3 4 5]]


In [ ]:
#3
import numpy as np
arr=np.arange(1,101).reshape(10,10)
print(arr)
arr_ravel=arr.ravel()
print(arr_ravel)
arr_flatten=arr.flatten()
print(arr_flatten)
# ravel is faster as it doesn't make a copy.
#it will modify the output id we change anything in the array but the flatten will not.

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40

In [ ]:
import numpy as np
image_matrix=np.random.randint(0,256,(5,5))
print(image_matrix)
req_img=image_matrix[1:4,1:4]
print(req_img)
req_img_flattened=req_img.flatten()
print(req_img_flattened)
#reshaping will change the shape which means number of rows and columns without changing the order of elements.

[[ 71 216  35 249 149]
 [140 153  79  98 200]
 [108  59 182 120  99]
 [136 166 162 158   5]
 [239  26 137  34  32]]
[[153  79  98]
 [ 59 182 120]
 [166 162 158]]
[153  79  98  59 182 120 166 162 158]


In [ ]:
import numpy as np
image_matrix=np.random.randint(0,256,(3,4,4))
print(image_matrix)
image_matrix_reshaped=image_matrix.reshape(1,48)
print(image_matrix_reshaped)
image_matrix_reshaped=image_matrix.reshape(3,4,4)
print(image_matrix_reshaped)
#Flattening an RGB image into a 1D array disrupts its spatial relationships.
# but reshaping back to (3, 4, 4) restores the channel structure and spatial layout without any loss of information, provided the reshaping dimensions are compatible.

[[[237  16  63 185]
  [ 72 216 157  90]
  [187 190  15 157]
  [209  22  37 196]]

 [[188 166  78 179]
  [ 23 206 251  61]
  [194  99  23 124]
  [ 96 191  10 217]]

 [[148 181 189 253]
  [251  58  33  79]
  [208 168  36 145]
  [108 120 218 106]]]
[[237  16  63 185  72 216 157  90 187 190  15 157 209  22  37 196 188 166
   78 179  23 206 251  61 194  99  23 124  96 191  10 217 148 181 189 253
  251  58  33  79 208 168  36 145 108 120 218 106]]
[[[237  16  63 185]
  [ 72 216 157  90]
  [187 190  15 157]
  [209  22  37 196]]

 [[188 166  78 179]
  [ 23 206 251  61]
  [194  99  23 124]
  [ 96 191  10 217]]

 [[148 181 189 253]
  [251  58  33  79]
  [208 168  36 145]
  [108 120 218 106]]]


# **Universal Functions**

Q1) Given an array x = [1, 4, 9, 16, 25], compute the square root of each element in the array and print the result.

Q2) Create an array angles =[0, $\frac{\pi}{2}$, $\pi$, $\frac{3\pi}{2}$]
, calculate the sine of each angle and print the result.



Q3) Given two arrays a =[True, False, True] and b = [False, False, True], perform an element-wise logical AND operation and print the result.

Q4) Create two arrays x = [1, 2, 3, 4] and y = [2, 2, 3, 5], perform an element-wise comparison (x < y) and print the result.

Q5) Create an array x =[-2, -1, 0, 1, 2, 3, 4], compute the following element-wise operation:

* If an element is negative, square it.
* If an element is non-negative, compute its exponential.
Print the resulting array.

In [ ]:
import numpy as np
x=np.array([1,4,9,16,25])
print(np.sqrt(x))

[1. 2. 3. 4. 5.]


In [ ]:
import numpy as np
angles=np.array([0,np.pi/2,np.pi,3*np.pi/2])
print(np.sin(angles))

[ 0.0000000e+00  1.0000000e+00  1.2246468e-16 -1.0000000e+00]


In [35]:
import numpy as np
a=np.array([True,False,True])
b=np.array([False,False,True])
print(np.logical_and(a,b))


[False False  True]


In [ ]:
import numpy as np
x=np.array([1,2,3,4])
y=np.array([2,2,3,5])
print(np.less(x,y))


[ True False False  True]


In [ ]:
import numpy as np
x=np.array([-2,-1,0,1,2,3,4])
print(np.where(x<0,x**2,np.exp(x)))

[ 4.          1.          1.          2.71828183  7.3890561  20.08553692
 54.59815003]


# **Aggregations**

####1. Generate a random array of size 10.
 calculate the following:
- Print the array
- The sum of all elements.
- The mean of the array.
- The standard deviation.
- Find 5$*$Minimum -3$*$Maximum

####2. Generate a 4x5 matrix with random integers between 1 and 50.
- Print the matrix.
- Compute the mean of all elements in the matrix.
- Compute the sum of each row in the matrix.

####3. Generate a random 3x3 matrix with random integers between 1 to 10
- Find the minimum value in each column and store it in a separate list min.
- Find the maximum value in each row and store it in a separate list max.
- Find the value of minimum of list max - maximum of list min.

####4. Given the array : data = np.array([15, 25, 35, 45, 55, 65]):
- Find the minimum value.
- Subtract this minimum value from all elements of the array and then calculate the mean of the resulting array.

####5. Given the array : arr = np.array([3, 5, 7, 9, 11]):
- Compute the cumulative sum of the elements.
- Compute the cumulative product of the elements.

####6. Imagine you have a dataset representing the scores of 4 students in 3 subjects:
scores = np.array([[85, 92, 78], [88, 76, 95], [91, 89, 82], [75, 85, 88]])
- Compute the average score for each student.
- Compute the highest score in each subject.
- Determine the overall average score for all students across all subjects.

In [ ]:
import numpy as np
arr=np.random.randint(1,10,10)
max_arr=np.max(arr)
min_arr=np.min(arr)
print(arr)
print(np.sum(arr))
print(np.mean(arr))
print(np.std(arr))
print(5*(min_arr)-3*(max_arr))

[7 5 2 8 6 9 5 2 8 5]
57
5.7
2.2825424421026654
-17


In [ ]:
import numpy as np
matrix=np.random.randint(1,50,(4,5))
print(matrix)
print(np.mean(matrix))
print(np.sum(matrix,axis=1))

[[28  9  7 16  5]
 [ 2 20  7 36  3]
 [41 46 36 19 30]
 [17 32  6 11 22]]
19.65
[ 65  68 172  88]


In [48]:
import numpy as np
arr=np.random.randint(1,10,(3,3))
print(arr)
min=np.min(arr,axis=0)
print(min)
max=np.max(arr,axis=1)
print(max)
print(np.min(max)-np.max(min))

[[4 5 9]
 [3 3 5]
 [3 8 4]]
[3 3 4]
[9 5 8]
1


In [ ]:
import numpy as np
data=np.array([15,25,35,45,55,65])
print(np.min(data))
print(np.mean(data-np.min(data)))

15
25.0


In [ ]:
import numpy as np
arr=np.array([3,5,7,9,11])
print(np.cumsum(arr))
print(np.cumprod(arr))

[ 3  8 15 24 35]
[    3    15   105   945 10395]


In [ ]:
import numpy as np
scores = np.array([[85, 92, 78], [88, 76, 95], [91, 89, 82], [75, 85, 88]])
print(np.mean(scores,axis=1))
print(np.max(scores,axis=0))
print(np.mean(scores))

[85.         86.33333333 87.33333333 82.66666667]
[91 92 95]
85.33333333333333


Section 8: Broadcasting in NumPy
1. Given two arrays:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) (shape: (3, 3)) B = np.array([10, 20, 30]) (shape: (3,)) Perform elementwise addition of A and B using broadcasting and print the result.

What is the resulting shape?

2. Write a function check_broadcasting(shape1, shape2) that:
Accepts two shapes as input and checks if they are broadcast-compatible. Use the function to test the following shape pairs: (3, 4) and (4,) (2, 1, 5) and (3, 5) (2, 3) and (2,)

For each case:

State whether broadcasting is possible.

If possible, state the resulting shape of the operation

3. Create a 2D array A of shape (3, 5) with random integers between 1 and 10.
Create a 1D array B of shape (5,) with random integers between 1 and 5. Use broadcasting to subtract B from each row of A and print the result.

4. Create a 3D array A with shape (2, 4, 3) filled with random integers between 0 and 10.
Create an array B of shape (4, 3) containing a constant value of 5.
Use broadcasting to add B to each 2D array slice of A.
Print the result
5. : You are given a grayscale image of shape (32, 32), where each pixel value is an integer. You want to apply a scaling factor of 0.5 to all the pixel values using broadcasting.
Use broadcasting to scale the image by multiplying it with the scaling factor 0.5.
Verify that the pixel values of the image are halved by printing the scaled image.
6. Calculate the distance between an observation point and a set of code points (codes). The goal is to find the closest code to the observation by calculating the Euclidean distance between each code and the observation.
Given two arrays :
codes = np.array([ [1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0], [1.0, 1.0, 1.0], [2.0, 3.0, 4.0] ])

observation = np.array([3.0, 3.0, 3.0])

Use broadcasting to calculate the squared Euclidean distance between the observation and each code.
Find and print the index of the closest code to the observation.
Print the distance between the observation and the closest code.
HINT : use np.argmin() to find the index of the closest code

In [18]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([10,20,30])
print(A+B)

[[11 22 33]
 [14 25 36]
 [17 28 39]]


In [24]:
import numpy as np

def check_broadcasting(shape1, shape2):
    try:
        result = np.broadcast_arrays(np.empty(shape1), np.empty(shape2))
    except ValueError:
        return False
    return True
print(check_broadcasting((3,4),(4,)))
print(check_broadcasting((2,1,5),(3,5)))
print(check_broadcasting((2,3),(2,)))



True
True
False


In [25]:
import numpy as np
A=np.random.randint(1,10,(3,5))
B=np.random.randint(1,5,(5,))
print(A)
print(B)
print(A-B)

[[1 7 7 2 9]
 [8 9 2 4 6]
 [6 5 2 5 4]]
[2 3 1 2 4]
[[-1  4  6  0  5]
 [ 6  6  1  2  2]
 [ 4  2  1  3  0]]


In [29]:
import numpy as np
A=np.random.randint(0,10,(2,4,3))
B=np.array([5])
print(A)
print(B)
print(A+B)

[[[4 7 1]
  [2 1 8]
  [1 4 9]
  [0 2 4]]

 [[1 9 7]
  [7 2 4]
  [5 8 3]
  [9 9 1]]]
[5]
[[[ 9 12  6]
  [ 7  6 13]
  [ 6  9 14]
  [ 5  7  9]]

 [[ 6 14 12]
  [12  7  9]
  [10 13  8]
  [14 14  6]]]


In [36]:
import numpy as np
image=np.random.randint(0,256,(32,32))
print(image)
scaled_image=image*0.5
print(scaled_image)




[[ 34  33 115 ... 113 102 182]
 [110 207 171 ...  21  70 188]
 [145 198 115 ... 151  82   1]
 ...
 [ 77  57  74 ...  32 229  28]
 [219  87  66 ... 244  67  99]
 [  0 219 179 ... 145  57 141]]
[[ 17.   16.5  57.5 ...  56.5  51.   91. ]
 [ 55.  103.5  85.5 ...  10.5  35.   94. ]
 [ 72.5  99.   57.5 ...  75.5  41.    0.5]
 ...
 [ 38.5  28.5  37.  ...  16.  114.5  14. ]
 [109.5  43.5  33.  ... 122.   33.5  49.5]
 [  0.  109.5  89.5 ...  72.5  28.5  70.5]]


In [39]:
import numpy as np
codes = np.array([[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0,8.0,9.0],[1.0,1.0,1.0],[2.0,3.0,4.0]])
observation = np.array([3.0, 3.0, 3.0])
squared_distances = np.sum((codes - observation)**2, axis=1)
closest_code_index = np.argmin(squared_distances)
closest_code = codes[closest_code_index]
print("Closest code to the observation:", closest_code)
print("Distance between the observation and the closest code:", squared_distances[closest_code_index])

Closest code to the observation: [2. 3. 4.]
Distance between the observation and the closest code: 2.0


# Concatenation

1. Write a program to vertically stack arrays using `np.vstack` and print the result: (Use any three 1D arrays) <br/>
<br/>
2. Write a program to horizontally stack arrays using `np.hstack`. Print the result: (Use any three 1D arrays) <br/>
<br/>
3. Given two 2D arrays of the same row size, horizontally stack them using `np.hstack` and print the result:<br/>
`m = np.array([[2, 4], [3, 6]])`<br/>
`n = np.array([[4, 8], [5, 10]])`<br/>
<br/>
4. Using `np.vstack`, stack the following arrays vertically and print the results:<br/>
`a = np.array([11, 12, 13])`<br/>
`b = np.array([[14, 15, 16], [17, 18, 19]])`<br/>
<br/>
5. Concatenate the following 2D arrays along different axes using `np.concatenate`. Demonstrate how to concatenate them along axis 0 and axis 1.<br/>
`x = np.array([[1, 2], [3, 4]])`<br/>
`y = np.array([[5, 6], [7, 8]])`<br/>
`z = np.array([[9, 10], [11, 12]])`<br/>

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
print(np.vstack((a,b,c)))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.array([7,8,9])
print(np.hstack((a,b,c)))

[1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np
m = np.array([[2, 4], [3, 6]])
n = np.array([[4, 8], [5, 10]])

print(np.hstack((m,n)))

[[ 2  4  4  8]
 [ 3  6  5 10]]


In [ ]:
import numpy as np
a = np.array([11, 12, 13])
b = np.array([[14, 15, 16], [17, 18, 19]])


print(np.vstack((a,b)))

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [ ]:
import numpy as np
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
z = np.array([[9, 10], [11, 12]])
print(np.concatenate((x,y,z),axis=0))
print(np.concatenate((x,y,z),axis=1))



[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]


# Boolean Masking

1. Use Boolean masking to filter elements from a 1D array:
Write a program to create a 1D array and use Boolean masking to filter out all elements greater than 5.<br/>

2. Apply a Boolean mask to a 2D array:
Given the 2D array below, create a Boolean mask to select all elements greater than 10 and print the masked elements.<br/>
`arr = np.array([[5, 12, 18], [7, 1, 3], [11, 6, 14]])`
 <br/>
3. Create a Boolean mask using a condition on an array:
Create a 1D array of integers from 0 to 10. Use a Boolean mask to filter out all even numbers and print the result.<br/>
Example:
`arr = np.arange(11)`
<br/>
4. Combine Boolean masks using logical operations:
Given the array below, create and combine two Boolean masks:<br/>
One mask selects elements greater than 5.
The other mask selects elements divisible by 3.
Combine the masks using logical AND and print the result.
Example:
`arr = np.array([1, 3, 6, 9, 12, 15])`
<br/>
5. Mask elements in a 2D array and replace them:
Write a program to replace all elements less than 5 in the 2D array below with 0 using Boolean masking.
<br/>
6.  Count elements satisfying a condition using Boolean masks:
Write a program to count how many elements in the array below are greater than 5.
<br/>

In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9])
mask=arr>5
print(arr[mask])



[6 7 8 9]


In [ ]:
import numpy as np
arr = np.array([[5, 12, 18], [7, 1, 3], [11, 6, 14]])
mask=arr>10
print(arr[mask])




[12 18 11 14]


In [ ]:
import numpy as np
arr=np.arange(11)
mask=arr%2==0
print(arr[mask])

[ 0  2  4  6  8 10]


In [ ]:
import numpy as np
arr = np.array([1, 3, 6, 9, 12, 15])
mask1=arr>5
mask2=arr%3==0
print(arr[mask1&mask2])

[ 6  9 12 15]


In [ ]:
import numpy as np
arr = np.array([[17, 5, 45], [74, 13, 3], [11, 61, 14]])
mask=arr<5
arr[mask]=0
print(arr)

[[17  5 45]
 [74 13  0]
 [11 61 14]]


In [49]:
import numpy as np
arr = np.array([1, 3, 6, 9, 12, 15])
mask=arr>5
print(np.sum(mask))

4
